config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :products do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'follows', on: :member
    get 'followers', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # primary_class?
 primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :product
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    attachment :image
    belongs_to :user, optional: true
    has_many :favorites
    has_many :comments, dependent: :destroy
    with_options presence: true do
        validates :title
        validates :content
        validates :tech
        validates :span
        validates :image
        validates :commitment
    end

    def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end

    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  validates :username, presence: true
  has_many :products, dependent: :destroy

  has_many :favorites
  has_many :favorite_products, through: :favorites, source: :product
  
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def already_favorited?(product)
    self.favorites.exists?(product_id: product.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @comment = current_user.comments.new(comment_params)
    @comment.product_id = @product.id
    if @comment.save
      flash.now[:notice] = "コメントを投稿しました"
      render :product_comments
    else
      render :error
    end
  end

  def destroy
    Comment.find_by(id: params[:id], product_id: params[:product_id]).destroy
    flash.now[:alert] = "投稿を消去しました"
    @product = Product.find(params[:product_id])
    render :product_comments
  end

  private
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    favorite = current_user.favorites.new(product_id: @product.id)
    favorite.save
  end

  def destroy
    @product = Product.find(params[:product_id])
    favorite = current_user.favorites.find_by(product_id: @product.id)
    favorite.destroy
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to product_path(@product), notice:"プロダクトを投稿しました."
    else
      render :new
    end
  end
  
  def index
    @products = Product.all
    @products = @products.where('location LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end

  def show
    @product = Product.find(params[:id])
    @comment = Comment.new
  end
  def edit
    @product = Product.find(params[:id])
    if @product.user != current_user
      redirect_to product_path, alert: "不正なアクセスです"
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path(@product), notice: "プロダクトを編集しました"
    else
      render :edit
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to user_path(product.user), notice: "プロダクトを削除しました。"
  end

  private
    def product_params
      params.require(:product).permit(:title, :content, :tech, :span, :image, :github, :link, :commitment)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to users_path, notice: "フォローしました"
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to users_path,notice: "フォロー解除しました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @favorite_products = @user.favorite_products
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to :users_path, alert: "不正なアクセスです"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
  <%= form_with(model:[product, comment], local:false ) do |f| %>
  <div id="comments_error">
    <%= render 'layouts/error_messages', model: f.object %>
  </div>
    <%= f.text_area :comment, :size=>"60x3",placeholder: "コメントをここ" %>
    <%= f.submit "送信する", class: "btn btn-success mb-4" %>
  <% end %>

app/views/comments/_product_comments.html.erb
 <% if @product.comments.present? %>
      <p>コメント件数:<%= @product.comments.count %></p>
        <% @product.comments.each do |comment| %>
        <div class="comments-index mb-2">
            <%= link_to comment.user.username, user_path(comment.user.id) %>
            <%= comment.created_at.strftime('%Y/%m/%d') %> <br>
            <div class="d-flex">
              <p><%= comment.comment%></p>
              <% if comment.user == current_user %>
                <div class="comment-delete">
                  <%= button_to "削除する", product_comment_path(comment.product, comment), method: :delete, remote: true, data: {cofirm: "本当に削除しますか?"}  %>
                </div>
            </div> 
        </div>
        <% end %>
    <% end %>
    <% else %>
    <p>コメントはまだありません</p>
  <% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/error.js.erb
$("#comments_error").html("<%= j(render 'layouts/error_messages', model: @comment) %>");

app/views/comments/product_comments.js.erb
$("#comments_area").html("<%= j(render 'comments/product_comments', product: @product, comment: @comment) %>");
$("textarea").val('');

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
    <% if product.favorited_by?(current_user) %>
            <%= link_to product_favorites_path(product) , method: :delete, remote: true do %>
            <span><i class="fa fa-heart unlike-btn"></i></span>
        <% end %>
        <span><%= product.favorites.count%></span>
        <% else %>
            <%= link_to product_favorites_path(product), method: :post, remote: true do %>
               <span><i class="fa fa-heart like-btn"></i></span>
        <% end %>
        <span><%= product.favorites.count%></span>
<% end %>
<% else %>
<p><span>いいね数</span><%= product.favorites.count%></p>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @product.id %>').html("<%= j(render "favorites/favorite", product: @product) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @product.id %>').html("<%= j(render "favorites/favorite", product: @product) %>");

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert">
    <div class="list-unstyled">
        <h5><%= model.errors.count%>件のエラー</h5>
        <%= model.errors.full_messages.each do |message| %>
            <li><%= message%></li>
        <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <script src="/js/custom.js"></script>
  </head>

  <body>
  <% if flash[:notice] %>
    <div class="notification is-info">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="notification is-danger">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>
  <nav class="navbar is-warning">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item"  do %>
        <h1 class="title is-4" style="font-family: cursive;">portfolio-land</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarMenuHeroC">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
    <% if user_signed_in? %>
      <div id="navbarMenuHeroC" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to 'プロダクト一覧', products_path, class: "navbar-item button is-white is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to 'プロダクト投稿', new_product_path, class: "navbar-item button is-white is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to 'プログラマー一覧', users_path, class: "navbar-item button is-white is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to 'マイページ', user_path(current_user), class: "navbar-item button is-white is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "navbar-item button is-white is-light" %>
        </div>
      </div>
      <% else %>
      <div class="navbar-menu" id="navbarMenuHeroC">
        <div class="navbar-item">
          <%= link_to "プロダクト一覧", products_path, class:"navbar-item button is-white is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "プログラマー一覧", users_path, class:"navbar-item button is-white is-light" %>
        </div>
        
              <div class="navbar-item">
                <%= link_to 'ログイン', new_user_session_path, class: "navbar-item button is-white is-light"  %>
             </div>
              <div class="navbar-item">
                <%= link_to '新規登録', new_user_registration_path, class:"navbar-item button is-white is-light" %>
              </div>
     
    <% end %>
  </nav>

    <%= yield %>
  </body>
</html>

app/views/products/_list.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <% @products.each do |product| %>
                <div class="column is-4">
                    <div class="card">
                        <div class="card-image">
                          <figure class="image is-4by3">
                            <%= link_to product_path(product) do %>
                                <%= attachment_image_tag product, :image %>
                            <% end %>
                          </figure>
                        </div>
                         <div id="favorite_buttons_<%= product.id%>">
                          <%= render 'favorites/favorite', product: product %>
                        </div>
                        <div class="media-content">
                            <div class="media">
                                <div class="media-left">
                                    <figure class="image is-48x48">
                                        <%= attachment_image_tag product.user, :profile_image, fallback: "no-image.png" %>
                                    </figure>
                                </div>
                                <div class="media-content">
                                    <div class="title"><%= link_to product.user.username, user_path(product.user) %></div>
                                </div>

                             <% if user_signed_in? %>
                              <% if current_user != product.user %>
                                <% if product.user.followed_by?(current_user) %>
                                    <p><%= button_to 'フォロー済み', user_relationships_path(product.user.id), class:"button is-success", method: :delete %></p>
                                  <% else %>
                                    <p><%= button_to "フォローする", user_relationships_path(product.user.id), class:"button is-success",method: :post %></p>
                                <% end %>
                              <% end %>
                            <% else %>
                            <% end %>
                            </div>


                            <div class="content">
                                <time><%= product.updated_at.strftime("%Y-%m-%d %H:%M")%></time>更新
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/products/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        プロダクト一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <% @products.each do |product| %>
                <div class="column is-4">
                    <div class="card">
                        <div class="card-image">
                          <figure class="image is-4by3">
                            <%= link_to product_path(product) do %>
                                <%= attachment_image_tag product, :image %>
                            <% end %>
                          </figure>
                        </div>
                         <div id="favorite_buttons_<%= product.id%>">
                          <%= render 'favorites/favorite', product: product %>
                        </div>
                        <div class="media-content">
                            <div class="media">
                                <div class="media-left">
                                    <figure class="image is-48x48">
                                        <%= attachment_image_tag product.user, :profile_image, fallback: "no-image.png" %>
                                    </figure>
                                </div>
                                <div class="media-content">
                                    <div class="title"><%= link_to product.user.username, user_path(product.user) %></div>
                                </div>

                             <% if user_signed_in? %>
                              <% if current_user != product.user %>
                                <% if product.user.followed_by?(current_user) %>
                                    <p><%= button_to 'フォロー済み', user_relationships_path(product.user.id), class:"button is-success", method: :delete %></p>
                                  <% else %>
                                    <p><%= button_to "フォローする", user_relationships_path(product.user.id), class:"button is-success",method: :post %></p>
                                <% end %>
                              <% end %>
                            <% else %>
                            <% end %>
                            </div>


                            <div class="content">
                                <time><%= product.updated_at.strftime("%Y-%m-%d %H:%M")%></time>更新
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/products/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        プロダクトの詳細
      </h1>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
                <%= attachment_image_tag @product, :image %>
            </figure>
          </div> 
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                  <p class="title is-4"><%= @product.title %></p>
                </div>
              </div>
              <div class="content">
                <table class="table is-narrow">
                  <tr>
                    <th>アプリの説明</th>
                  </tr>
                  <tr>
                    <td><%= simple_format @product.content %></td>
                  </tr>
                  <tr>
                    <th>アプリの制作期間</th>
                  </tr>
                  <tr>
                    <td><%=@product.span %></td>
                  </tr>
                  
                  <tr>
                    <th>技術スタック</th>
                  </tr>
                  <tr>
                    <td><%= simple_format @product.tech %></td>
                  </tr>

                  <tr>
                    <th>githubのリンク</th>
                  </tr>
                  <tr>
                    <td><%= simple_format @product.github %></td>
                  </tr>

                  <tr>
                    <th>リンク</th>
                  </tr>
                  <tr>
                    <td><%= simple_format @product.link %></td>
                  </tr>

                  <tr>
                    <th>こだわり</th>
                  </tr>
                  <tr>
                    <td><%= simple_format @product.commitment %></td>
                  </tr>
                  


                </table>
                 <div id="favorite_buttons_<%= @product.id %>">
                    <%= render 'favorites/favorite', product: @product %>
                  </div>
                <% if @product.user.id == current_user.id %>
                  <%= link_to '編集画面', edit_product_path(@product), class:"button is-success" %>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @product.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @product.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@product.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @product.user.username %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>
<div class="new-comment">
  <%= render 'comments/form', product: @product, comment: @comment %>
</div>
<div id="comments_area">
  <%= render 'comments/product_comments', product: @product %>
</div>

app/views/relationships/_follow.html.erb
<% if user_signed_in? %>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <%= button_to user_relationships_path(user),class:"button is-success",method: :delete, remote: true do %>
                <span>フォロー済み</span>
            <% end %>
        <% else %>
            <%= button_to user_relationships_path(user), class:"button is-success",method: :post, remote: true do %>
                <span>フォローする</span>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/users/_follow.html.erb
<!-- フォローボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
  <%= hidden_field_tag :following_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/_unfollow.html.erb
<!-- フォロー解除ボタン ------------------------------------------------------------------>
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn btn-outline-secondary" %>
<% end %>

app/views/users/followers.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWERS</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                 <div class="column is-4">
                    <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
                        <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
                    </figure>
                  </div>
                 <td class="is-size-4">
                    <strong><%= user.username%></strong>
                  </td>
                <% end %>
              </td>
            <td>
              <% if current_user != user %>
                <% if user.followed_by?(current_user) %>
                  <p><%= button_to "フォロー済み", user_relationships_path(user.id), class:"button is-success", method: :delete %></p>
              <% else %>
                  <p><%= button_to 'フォローする', user_relationships_path(user.id),  class:"button is-success",method: :post %></p>
                <% end %>
              <% end %>
            <% end %>
            
            </td>  
          </tr>            
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container marketing">
    <div class="row d-flex justify-content-center">
        <div class="col-10 mt-5">
            <h1>FOLLOWS</h1>
            <table class="table text-center">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <tr>
                        
                            <td>
                                <%= link_to user_path(user) do %>
                                
                                <div class="column is-4">
                                    <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
                                        <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
                                    </figure>
                                </div>
                                
                                   <td class="is-size-4">
                                        <strong><%= user.username%></strong>
                                    </td>
                                <% end %>
                            </td>
                            <td>
                                <% if current_user != user %>
                                    <% if user.followed_by?(current_user) %>
                                        <p><%= button_to 'フォロー済み', user_relationships_path(user.id), class:"button is-success",method: :delete %></p>
                                    <% else %>
                                        <p><%= button_to 'フォローする', user_relationships_path(user.id), class:"button is-success",method: :post %></p>
                                    <% end %>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<section class="hero is-success">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                my page
            </h1>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
          <div class="column is-8">
           <div class="columns is-centered">
            <div class="column is-4">
                <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
                    <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
                </figure>
            </div>
            <div class="column is-8">
                <table class="table is-fullwidth">
                    <tr>
                        <td class="is-size-4">
                            <strong><%= @user.username%></strong>
                        </td>
                        <% if @user.id == current_user.id %>
                        <td class="is-size-4">
                            <%= @user.email%>
                        </td>
                        <td>
                            <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                        </td>
                        <% end %>
                    </tr>
                </table>
                <table class="table is-fullwidth">
                    <tr>
                        <td>
                            <%= @user.profile%>
                        </td>
                    </tr>
                </table>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <% @user.products.each do |product| %>
                <div class="column is-4">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image is-4by3">
                                <%= link_to product_path(product) do %>
                                    <%= attachment_image_tag product, :image, fallback: "no-image.png" %>
                                <% end %>
                            </figure>
                        </div>
                        <p><%= link_to 'フォロー', follows_user_path(@user.id) %></p>
                        <p><%= link_to 'フォロワー',followers_user_path(@user.id) %></p>
                        <% if current_user != @user %>
                          <% if @user.followed_by?(current_user) %>
                            <span><p><%= button_to 'フォロー済み', user_relationships_path(@user.id), class:"button is-success" ,method: :delete %></p></span>
                            <% else %>
                            <span><p><%= button_to 'フォローする', user_relationships_path(@user.id), class:"button is-success",method: :post %></p></span>
                          <% end %>
                        <% end %>
                            <div class="card-content">
                                <div class="media">
                                    <div class="media-content">
                                        <%= link_to product_path(product), class: "panel-block" do %>
                                            <span class="panel-icon">
                                                <i class="fas fa-book" aria-hidden="true"></i>
                                            </span>
                                            このプロダクトを見る
                                        <% end %>
                                        <% if @user.id == current_user.id %>
                                            <%= link_to edit_product_path(product), class: "panel-block" do %>
                                                <span class="panel-icon">
                                                    <i class="fas fa-edit"></i>
                                                </span>
                                                このプロダクトを編集する
                                            <% end %>
                                            <%=link_to product_path(product), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                                                <span class="panel-icon">
                                                    <i class="fas fa-trash"></i>
                                                </span>
                                                    このプロダクトを削除する
                                            <% end %>
                                        <% end %>
                                    </div>
                                </div>
                               
                                <div class="content">
                                    <time><%= product.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                                </div>
                                <% @favorite_products.each do |product| %>
                                <hr>
                                <p><span>ファボツイート</span><%= link_to product.title, product_path(product.id) %></p>
                                <% end %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
   </section>